// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnrta6WZ3wUCgltiLcOEyBepSWK_8iIVE',
    appId: '1:971949985740:web:ab904392bb44b17bd05769',
    messagingSenderId: '971949985740',
    projectId: 'learncrud-17635',
    authDomain: 'learncrud-17635.firebaseapp.com',
    storageBucket: 'learncrud-17635.appspot.com',
    measurementId: 'G-00X4QHTVZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsmoEK-wpSdGFrGCeCWRlpyxqilRElCm8',
    appId: '1:971949985740:android:d62a427c0049a41cd05769',
    messagingSenderId: '971949985740',
    projectId: 'learncrud-17635',
    storageBucket: 'learncrud-17635.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9JsRIMRBuiLC3aoqRZK9hJCPMFw7Kmzc',
    appId: '1:971949985740:ios:f8085cadc64ce38cd05769',
    messagingSenderId: '971949985740',
    projectId: 'learncrud-17635',
    storageBucket: 'learncrud-17635.appspot.com',
    iosBundleId: 'com.example.crudfb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9JsRIMRBuiLC3aoqRZK9hJCPMFw7Kmzc',
    appId: '1:971949985740:ios:94216c54e6371359d05769',
    messagingSenderId: '971949985740',
    projectId: 'learncrud-17635',
    storageBucket: 'learncrud-17635.appspot.com',
    iosBundleId: 'com.example.crudfb.RunnerTests',
  );
}
